"""Because groupby was used, the sentences for the pattern stats was lost.
It seems a bit too complex to figure out how to include them, so I will add
sentences to the stats file generated by tuple_pattern_stats here.
"""
import pandas as pd

def get_sentence(df, df2_dict_item):
    UPOS_child = df2_dict_item['UPOS_child']
    UPOS_parent = df2_dict_item['UPOS_parent']
    DEPREL_child = df2_dict_item['DEPREL_child']
    direction = df2_dict_item['direction']
    english_example = df2_dict_item['surface_order_parent/child_forms']
    arabic_example = df2_dict_item['arabic_example_surface_order_parent/child_forms']
    
    if UPOS_parent == '---':
        return df[(df['UPOS_child'] == UPOS_child)&
            (df['DEPREL_child'] == DEPREL_child) &
            (df['direction'] == direction) &
            (df['surface_order_parent/child_forms'] == english_example) &
            (df['arabic_example_surface_order_parent/child_forms'] == arabic_example)].to_dict('records')[0]['full_sentence_arabic_parent']
    
    return df[(df['UPOS_child'] == UPOS_child)&
        (df['UPOS_parent'] == UPOS_parent) &
        (df['DEPREL_child'] == DEPREL_child) &
        (df['direction'] == direction) &
        (df['surface_order_parent/child_forms'] == english_example) &
        (df['arabic_example_surface_order_parent/child_forms'] == arabic_example)].to_dict('records')[0]['full_sentence_arabic_parent']


if __name__ == '__main__':
    df = pd.read_csv('./data/patterns/pattern_list_full_test.tsv', sep='\t')
    df2 = pd.read_csv('./data/patterns/pattern_list_stats_wo_sent.tsv', sep='\t')
    
    arabic_sentences = [get_sentence(df, x.to_dict()) for i, x in df2.iterrows()]
    df2['full_sentences'] = arabic_sentences
    
    df2.to_csv('./data/patterns/new_stats_w_sents.tsv', sep='\t')